# Generated by Django 4.2 on 2023-04-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ValorantLineups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/abilities')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/maps')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(default='', upload_to='static/agents'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=254)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValorantLineups.ability')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValorantLineups.agent')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValorantLineups.map')),
            ],
        ),
        migrations.AddField(
            model_name='ability',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValorantLineups.agent'),
        ),
    ]
