# Generated by Django 4.2 on 2023-04-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValorantLineups', '0002_ability_map_role_agent_image_video_ability_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='part',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='map',
            name='side',
            field=models.CharField(choices=[('all', 'All'), ('attack', 'Attack'), ('defense', 'Defense')], default='all', max_length=10),
        ),
    ]
