# Generated by Django 4.2 on 2023-04-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValorantLineups', '0004_remove_map_side_video_part_video_side_alter_map_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(default=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='agent',
            name='race',
            field=models.CharField(choices=[('human', 'Human'), ('radiant', 'Radiant'), ('cybernetic', 'Cybernetic')], default='Human', max_length=30),
        ),
        migrations.AddField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('human', 'Human'), ('radiant', 'Radiant'), ('cybernetic', 'Cybernetic')], default='Human', max_length=30),
        ),
        migrations.AlterField(
            model_name='map',
            name='part',
            field=models.CharField(choices=[('a b', 'A, B'), ('a b c', 'A, B, C')], max_length=50),
        ),
    ]
