# Generated by Django 4.2 on 2023-04-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValorantLineups', '0006_alter_agent_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
