# Generated by Django 4.2 on 2023-04-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValorantLineups', '0007_alter_agent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='race',
            field=models.CharField(choices=[('Controllers', 'Controllers'), ('duelists', 'Duelists'), ('initiators', 'Initiators'), ('sentinels', 'Sentinel')], default='Unknown', max_length=30),
        ),
    ]
