# Generated by Django 4.2 on 2023-04-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValorantLineups', '0009_alter_agent_race_alter_agent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='card_image',
            field=models.ImageField(default=models.ImageField(upload_to='static/agents'), upload_to='static/agents'),
        ),
    ]
