# Generated by Django 4.2 on 2023-04-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValorantLineups', '0011_alter_agent_race_alter_agent_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
