# Generated by Django 4.2 on 2023-04-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValorantLineups', '0012_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='ability',
            field=models.CharField(choices=[('q', 'ability_1'), ('e', 'ability_2'), ('c', 'ability_3'), ('x', 'ability_4')], default='Select an ability', max_length=50),
        ),
    ]
