# Generated by Django 4.2 on 2023-04-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValorantLineups', '0015_video_type_alter_ability_name_alter_agent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='side',
        ),
    ]
