# Generated by Django 4.2 on 2023-05-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValorantLineups', '0017_contactrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='part',
            field=models.CharField(choices=[('all', 'All'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.CharField(choices=[('Setup', 'Setup'), ('Lineup', 'Lineup'), ('Mechanics', 'Mechanics')], max_length=50, null=True),
        ),
    ]
