# Generated by Django 4.2 on 2023-05-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValorantLineups', '0018_alter_video_part_alter_video_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='text',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='attach',
            field=models.FileField(null=True, upload_to='static/attachemts'),
        ),
        migrations.AlterField(
            model_name='video',
            name='part',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, null=True),
        ),
    ]
