# Generated by Django 4.2 on 2023-05-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ValorantLineups', '0019_remove_contactrequest_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrequest',
            name='attach',
        ),
    ]
