# Generated by Django 4.2 on 2023-05-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ValorantLineups', '0020_remove_contactrequest_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='attach',
            field=models.FileField(null=True, upload_to='static/attachemts'),
        ),
    ]
