# Generated by Django 4.2 on 2023-05-24 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ValorantLineups', '0022_starredvideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ValorantLineups.video')),
            ],
        ),
        migrations.DeleteModel(
            name='StarredVideos',
        ),
    ]
